### ISSUE TITLE
Doesn't install on Raspberry Pi 4B (8GB)

### ISSUE THREAD

**Issue by leecollings** [daibach142/FGFS_Saitek_Radio#6]
Hi there,

The first three steps as found in the INSTALL file do not work properly, and error out.

the intiial ./configure does ask for the device ID and IP address (which I used the default and then 127.0.0.1 for IP).

However, the make command spits out a bunch of errors, after that the sudo make install command complains that the directory doesn't exist. Finally, the StartRadioPanel command complains the command cannot be found.

Any ideas? 

```
lee@raspberrypi:~/Downloads/saitek_radio $ ./configure
Device address (default is /dev/hidraw0): /dev/hidraw0
Flightgear computer (default is 192.168.1.103): 127.0.0.1
StartRadioPanel created
lee@raspberrypi:~/Downloads/saitek_radio $ make
gcc *.c -o SaitekRadioPanel
/usr/bin/ld: /tmp/cc3C9ffc.o:(.bss+0x0): multiple definition of `device'; /tmp/ccpaHBed.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/cc3C9ffc.o:(.bss+0x18): multiple definition of `server'; /tmp/ccpaHBed.o:(.bss+0x18): first defined here
/usr/bin/ld: /tmp/cc3C9ffc.o:(.bss+0x2c): multiple definition of `STKRPInput'; /tmp/ccpaHBed.o:(.bss+0x2c): first defined here
/usr/bin/ld: /tmp/cc3C9ffc.o:(.bss+0x30): multiple definition of `FGFSInput'; /tmp/ccpaHBed.o:(.bss+0x30): first defined here
/usr/bin/ld: /tmp/ccucYfJd.o:(.bss+0x0): multiple definition of `device'; /tmp/ccpaHBed.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/ccucYfJd.o:(.bss+0x18): multiple definition of `server'; /tmp/ccpaHBed.o:(.bss+0x18): first defined here
/usr/bin/ld: /tmp/ccucYfJd.o:(.bss+0x2c): multiple definition of `STKRPInput'; /tmp/ccpaHBed.o:(.bss+0x2c): first defined here
/usr/bin/ld: /tmp/ccucYfJd.o:(.bss+0x30): multiple definition of `FGFSInput'; /tmp/ccpaHBed.o:(.bss+0x30): first defined here
/usr/bin/ld: /tmp/cckUY4Rb.o:(.bss+0x0): multiple definition of `device'; /tmp/ccpaHBed.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/cckUY4Rb.o:(.bss+0x18): multiple definition of `server'; /tmp/ccpaHBed.o:(.bss+0x18): first defined here
/usr/bin/ld: /tmp/cckUY4Rb.o:(.bss+0x2c): multiple definition of `STKRPInput'; /tmp/ccpaHBed.o:(.bss+0x2c): first defined here
/usr/bin/ld: /tmp/cckUY4Rb.o:(.bss+0x30): multiple definition of `FGFSInput'; /tmp/ccpaHBed.o:(.bss+0x30): first defined here
/usr/bin/ld: /tmp/cckHQ7Kc.o:(.bss+0x0): multiple definition of `device'; /tmp/ccpaHBed.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/cckHQ7Kc.o:(.bss+0x18): multiple definition of `server'; /tmp/ccpaHBed.o:(.bss+0x18): first defined here
/usr/bin/ld: /tmp/cckHQ7Kc.o:(.bss+0x2c): multiple definition of `STKRPInput'; /tmp/ccpaHBed.o:(.bss+0x2c): first defined here
/usr/bin/ld: /tmp/cckHQ7Kc.o:(.bss+0x30): multiple definition of `FGFSInput'; /tmp/ccpaHBed.o:(.bss+0x30): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:4: SaiteKRadioPanel] Error 1
lee@raspberrypi:~/Downloads/saitek_radio $ sudo make install
cp SaitekRadioPanel /usr/games
cp: cannot stat 'SaitekRadioPanel': No such file or directory
make: *** [Makefile:9: install] Error 1
lee@raspberrypi:~/Downloads/saitek_radio $ StartRadioPanel
bash: StartRadioPanel: command not found
lee@raspberrypi:~/Downloads/saitek_radio $ 
```

**Comment by daibach142** [comment]
Coding error now trapped by current gcc compiler - my bad!
Fixed in version 1.3

**Comment by leecollings** [comment]
Hi Dave,

I've come back to this, and even after your screenshot of compiling (using cargo), this still won't run on my Pi (I had to try installing cargo, but then complained about config files etc).

So would you be able to just simply help me with what I should be running in terminal to install this on a Pi please?

**Comment by leecollings** [comment]
I tried following the instructions in the INSTALL file, but I still receive the compile error after sudo make install

```
lee@raspberrypi:~/Downloads/FGFS_Saitek_Radio-master $ ./configure
The libudev version will determine the device name for the Saitek Radio Panel.
If not using the libudev version, determine the device address for the Saitek radio Panel
  by plugging it in and doing 'ls /dev/hid*'.
The Flightgear computer address is usually running on the same machine, so 127.0.0.1 
  is a suitably value. If Flightgear is running remotely, specify its address.
 
The full installation sequence (./configure; make; sudo make install) can be run
  whenever a configuration change is required.
 
Do you want the libudev version (y or n) (default is n): y
Flightgear computer (default is 127.0.0.1): 127.0.0.1
StartPanel created
lee@raspberrypi:~/Downloads/FGFS_Saitek_Radio-master $ make
make: 'SaitekRadioPanel' is up to date.
lee@raspberrypi:~/Downloads/FGFS_Saitek_Radio-master $ StartPanel
bash: StartPanel: command not found
lee@raspberrypi:~/Downloads/FGFS_Saitek_Radio-master $ sudo make install
cp SaitekRadioPanel /usr/games
cp StartPanel /usr/games
cp *.xml /usr/share/games/flightgear/Protocol
mkdir -p ~/.fgfs/Nasal
cp -r *.nas ~/.fgfs/Nasal
cp 55-saitekradiopanel.conf /usr/share/X11/xorg.conf.d
cp 55-saitek.rules /etc/udev/rules.d
udevadm control --reload
lee@raspberrypi:~/Downloads/FGFS_Saitek_Radio-master $ StartPanel
lee@raspberrypi:~/Downloads/FGFS_Saitek_Radio-master $ /usr/games/StartPanel: line 6: /usr/games/SaitekRadioPanel: cannot execute binary file: Exec format error
lee@raspberrypi:~/Downloads/FGFS_Saitek_Radio-master $ 
```

Any ideas?

**Comment by daibach142** [comment]
Hi Lee
Can we switch to using normal email please as it's very inconvenient for me to be in and out of Github (2 factor authetication)
My email is: dave@attwoods.org.uk - just send a 'hello' message to that address from your normal email
Thanks

Dave
